language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/psalm --shepherd

after_script:
  - bash <(curl -s https://codecov.io/bash)
